version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./datasets:/var/lib/neo4j/import
    
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./shared-volume:/app/shared-volume
    depends_on:
      - neo4j
      - postgres

volumes:
  neo4j_data:
  postgres_data:
  shared-volume:
